---
- name: Create node_exporter folder
  file:
    path: /opt/node_exporter
    state: directory

- name: Extract node_exporter
  unarchive:
    src: node_exporter-1.9.1.linux-amd64.tar.gz
    dest: /opt/node_exporter
    remote_src: no
    creates: /opt/node_exporter/node_exporter-1.9.1.linux-amd64

- name: Install binary
  copy:
    src: /opt/node_exporter/node_exporter-1.9.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes   # <--- MUY IMPORTANTE

- name: Deploy systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started

